enum Theme {
    Light,
    Dark,
}

struct ThemeVariables {
    bg_page1: String,
    bg_page2: String,
    bg_element1: String,
    bg_element2: String,
    bg_element3: String,
    bg_element4: String,
    bg_element5: String,
    bg_element6: String,
    bg_element7: String,
    bg_element8: String,
    bg_invert: String,
    bg_inline_code: String,
    bg_tag: String,
    text1: String,
    text2: String,
    text3: String,
    text4: String,
    border1: String,
    border2: String,
    border3: String,
    border4: String,
    primary1: String,
    primary2: String,
    destructive1: String,
    destructive2: String,
    button_text: String,
    slight_layer: String,
    opaque_layer: String,
    editor_footer: String,
    prism_bg: String,
    prism_default_text: String,
    prism_selection_bg: String,
    prism_code_1: String,
    prism_code_block_bg: String,
    prism_code_3: String,
    prism_code_2: String,
    prism_code_4: String,
    prism_code_5: String,
    prism_code_6: String,
    prism_code_7: String,
    prism_code_8: String,
    prism_code_9: String,
    prism_line_number: String,
}

fn get_theme_variable_sets(theme: Theme) -> ThemeVariables {
    match theme {
        Theme::Light => ThemeVariables {
            bg_page1: "#F8F9FA".to_string(),
            bg_page2: "#FFFFFF".to_string(),
            bg_element1: "#FFFFFF".to_string(),
            bg_element2: "#F8F9FA".to_string(),
            bg_element3: "#E9ECEF".to_string(),
            bg_element4: "#DEE2E6".to_string(),
            bg_element5: "#212529".to_string(),
            bg_element6: "#343A40".to_string(),
            bg_element7: "#FFFFFF".to_string(),
            bg_element8: "#FBFDFC".to_string(),
            bg_invert: "#1E1E1E".to_string(),
            bg_inline_code: "#E9ECEF".to_string(),
            bg_tag: "#F8F9FA".to_string(),

            text1: "#212529".to_string(),
            text2: "#495057".to_string(),
            text3: "#868E96".to_string(),
            text4: "#CED4DA".to_string(),
            border1: "#343A40".to_string(),
            border2: "#ADB5BD".to_string(),
            border3: "#DEE2E6".to_string(),
            border4: "#F1F3F5".to_string(),
            primary1: "#17098B".to_string(),
            primary2: "#2C1CAD".to_string(),
            destructive1: "#FF6B6B".to_string(),
            destructive2: "#FF8787".to_string(),
            button_text: "#FFFFFF".to_string(),

            slight_layer: "rgba(0, 0, 0, 0.05)".to_string(),
            opaque_layer: "rgba(249, 249, 249, 0.85)".to_string(),
            editor_footer: "#FFFFFF".to_string(),

            prism_bg: "#fbfcfd".to_string(),
            prism_default_text: "#24292e".to_string(),
            prism_selection_bg: "rgba(0, 0, 0, 0.15)".to_string(),
            prism_code_block_bg: "#fbfcfd".to_string(),
            prism_code_1: "#969896".to_string(),
            prism_code_2: "#24292e".to_string(),
            prism_code_3: "#a626a4".to_string(),
            prism_code_4: "#63a35c".to_string(),
            prism_code_5: "#0184bc".to_string(),
            prism_code_6: "#50a14f".to_string(),
            prism_code_7: "#a626a4".to_string(),
            prism_code_8: "#005cc5".to_string(),
            prism_code_9: "#a626a4".to_string(),
            prism_line_number: "#585c63".to_string(),
        },
        Theme::Dark => ThemeVariables {
            bg_page1: "#121212".to_string(),
            bg_page2: "#121212".to_string(),
            bg_element1: "#1E1E1E".to_string(),
            bg_element2: "#1E1E1E".to_string(),
            bg_element3: "#252525".to_string(),
            bg_element4: "#2E2E2E".to_string(),
            bg_element5: "#F1F3F5".to_string(),
            bg_element6: "#F8F9FA".to_string(),
            bg_element7: "#252525".to_string(),
            bg_element8: "#0c0c0c".to_string(),
            bg_invert: "#FFFFFF".to_string(),
            bg_inline_code: "#363636".to_string(),
            bg_tag: "#252525".to_string(),

            text1: "#ECECEC".to_string(),
            text2: "#D9D9D9".to_string(),
            text3: "#ACACAC".to_string(),
            text4: "#595959".to_string(),
            border1: "#E0E0E0".to_string(),
            border2: "#A0A0A0".to_string(),
            border3: "#4D4D4D".to_string(),
            border4: "#2A2A2A".to_string(),
            primary1: "#5E5B7B".to_string(),
            primary2: "#6A63AA".to_string(),
            destructive1: "#FFC9C9".to_string(),
            destructive2: "#FFA8A8".to_string(),
            button_text: "#121212".to_string(),

            slight_layer: "rgba(255, 255, 255, 0.1)".to_string(),
            opaque_layer: "rgba(0, 0, 0, 0.85)".to_string(),
            editor_footer: "#2E2E2E".to_string(),

            prism_bg: "#1E1E1E".to_string(),
            prism_default_text: "#e0e6f1".to_string(),
            prism_selection_bg: "#383e49".to_string(),
            prism_code_block_bg: "#1e1e1e".to_string(),
            prism_code_1: "#7c858d".to_string(),
            prism_code_2: "#abb2bf".to_string(),
            prism_code_3: "#e06c75".to_string(),
            prism_code_4: "#d19a66".to_string(),
            prism_code_5: "#98c379".to_string(),
            prism_code_6: "#56b6c2".to_string(),
            prism_code_7: "#c678dd".to_string(),
            prism_code_8: "#61afef".to_string(),
            prism_code_9: "#c678dd".to_string(),
            prism_line_number: "#5c6370".to_string(),
        },
    }
}
